CREATE TABLE ARTICULO (
	ID IDENTITY NOT NULL UNIQUE,
	TITULO VARCHAR2(255),
	CUERPO VARCHAR2(255),
	AUTOR_ID BIGINT NOT NULL,
	FECHA DATE NOT NULL,
)

CREATE TABLE ARTICULO_COMENTARIOS (
	ARTICULO_ID BIGINT NOT NULL UNIQUE,
	COMENTARIO_ID BIGINT NOT NULL UNIQUE
)

CREATE TABLE ARTICULO_ETIQUETAS (
	ARTICULO_ID BIGINT NOT NULL UNIQUE,
	ETIQUETA_ID BIGINT NOT NULL UNIQUE
)

CREATE TABLE COMENTARIO (
	ID IDENTITY NOT NULL UNIQUE,
	COMENTARIO VARCHAR2(255),
	AUTOR BIGINT NOT NULL,
	ARTICULO BIGIN NOT NULL
)

CREATE TABLE ETIQUETA (
	ID IDENTITY NOT NULL UNIQUE,
	ETIQUETA VARCHAR2(255)
)

CREATE TABLE USUARIO (
	ID IDENTITY NOT NULL UNIQUE,
	USERNAME VARCHAR2(255) NOT NULL UNIQUE,
	NOMBRE VARCHAR2(255) NOT NULL,
	PASSWORD VARCHAR2(255)NOT NULL,
	ADMINISTRATOR BOOLEAN NOT NULL,
	AUTOR BOOLEAN NOT NULL
)