CREATE TABLE IF NOT EXISTS ARTICULO (
  ID       BIGINT PRIMARY KEY AUTO_INCREMENT NOT NULL,
  TITULO   VARCHAR2(255)                     NOT NULL UNIQUE,
  CUERPO   VARCHAR2(255),
  AUTOR_ID BIGINT                            NOT NULL REFERENCES USUARIO (ID) ON UPDATE CASCADE ON DELETE CASCADE,
  FECHA    DATE                              NOT NULL
);

CREATE TABLE IF NOT EXISTS ARTICULO_COMENTARIOS (
  ID            BIGINT PRIMARY KEY AUTO_INCREMENT NOT NULL,
  ARTICULO_ID   BIGINT                            NOT NULL REFERENCES ARTICULO (ID) ON UPDATE CASCADE ON DELETE CASCADE,
  COMENTARIO_ID BIGINT                            NOT NULL REFERENCES COMENTARIO (ID) ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS ARTICULO_ETIQUETAS (
  ID          BIGINT PRIMARY KEY AUTO_INCREMENT NOT NULL,
  ARTICULO_ID BIGINT                            NOT NULL REFERENCES ARTICULO (ID) ON UPDATE CASCADE ON DELETE CASCADE,
  ETIQUETA_ID BIGINT                            NOT NULL REFERENCES ETIQUETA (ID) ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS COMENTARIO (
  ID          BIGINT PRIMARY KEY AUTO_INCREMENT NOT NULL,
  COMENTARIO  VARCHAR2(255),
  AUTOR_ID    BIGINT                            NOT NULL REFERENCES USUARIO (ID) ON UPDATE CASCADE ON DELETE CASCADE,
  ARTICULO_ID BIGINT                            NOT NULL
);

CREATE TABLE IF NOT EXISTS ETIQUETA (
  ID       BIGINT PRIMARY KEY AUTO_INCREMENT NOT NULL,
	ETIQUETA VARCHAR2(255)
);

CREATE TABLE IF NOT EXISTS USUARIO (
  ID            BIGINT PRIMARY KEY AUTO_INCREMENT NOT NULL,
	USERNAME VARCHAR2(255) NOT NULL UNIQUE,
	NOMBRE VARCHAR2(255) NOT NULL,
	PASSWORD VARCHAR2(255)NOT NULL,
	ADMINISTRATOR BOOLEAN NOT NULL,
	AUTOR BOOLEAN NOT NULL
);